# baseURL = "http://bitbay.market/"
baseURL = "/"
languageCode = "en-us"
title = "Bitbay.Market"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
theme = "bitbay"

[languages]
  [languages.en]
    title = "BitBay - Official Crypto-Currency Coin, Decentralized Markets, Unbreakable Smart Contracts - BitBay"
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    [languages.en.params]
      flagCode = 'gb'
  [languages.es]
    title = "BitBay - Official Crypto-Currency Coin, Decentralized Markets, Unbreakable Smart Contracts - BitBay"
    languageName = "Spanish"
    weight = 2
    contentDir = "content/es"
    [languages.es.params]
      flagCode = 'es'
  [languages.fr]
    title = "BitBay - Official Crypto-Currency Coin, Decentralized Markets, Unbreakable Smart Contracts - BitBay"
    languageName = "French"
    weight = 3
    contentDir = "content/fr"
    [languages.fr.params]
      flagCode = 'fr'
  [languages.ru]
    title = "BitBay - Official Crypto-Currency Coin, Decentralized Markets, Unbreakable Smart Contracts - BitBay"
    languageName = "Russian"
    weight = 4
    contentDir = "content/ru"
    [languages.ru.params]
      flagCode = 'ru'
  [languages.ja]
    title = "BitBay - Official Crypto-Currency Coin, Decentralized Markets, Unbreakable Smart Contracts - BitBay"
    languageName = "Japanese"
    weight = 5
    contentDir = "content/ja"
    [languages.ja.params]
      flagCode = 'jp'
  [languages.ko]
    title = "BitBay - Official Crypto-Currency Coin, Decentralized Markets, Unbreakable Smart Contracts - BitBay"
    languageName = "Korean"
    weight = 6
    contentDir = "content/ko"
    [languages.ko.params]
      flagCode = 'kr'
  [languages.ar]
    title = "قالب المقايضة - BitBay"
    languageName = "Arabic"
    weight = 7
    contentDir = "content/ar"
    [languages.ar.params]
      flagCode = 'sa'
  [languages.pl]
    title = "BitBay - Official Crypto-Currency Coin, Decentralized Markets, Unbreakable Smart Contracts - BitBay"
    languageName = "Polish"
    weight = 8
    contentDir = "content/pl"
    [languages.pl.params]
      flagCode = 'pl'


[[languages.en.menu.main]]
url    = "decentralized-marketplace"
name   = "Decentralized Marketplace"
weight = 1

[[languages.en.menu.main]]
url    = "features"
name   = "Features"
weight = 3

[[languages.en.menu.main]]
url    = "the-team"
name   = "The Team"
weight = 5

[[languages.en.menu.main]]
url    = "roadmap"
name   = "Roadmap"
weight = 7

[[languages.en.menu.main]]
url    = "downloads"
name   = "Downloads"
weight = 9


[[languages.en.menu.navmobile]]
url    = "https://forum.bitbay.market"
name   = "Community"
weight = 1

[[languages.en.menu.navmobile]]
url    = "https://wallet.bitbay.market"
name   = "Web Wallet"
weight = 3

[[languages.en.menu.navmobile]]
url    = "https://wallet.bitbay.market/buy.php"
name   = "Buy $BAY"
weight = 5


[[languages.es.menu.main]]
url    = "decentralized-marketplace"
name   = "BitBay Marketplace"
weight = 1

[[languages.es.menu.main]]
url    = "features"
name   = "Caracteristicas"
weight = 3

[[languages.es.menu.main]]
url    = "the-team"
name   = "El equipo"
weight = 5

[[languages.es.menu.main]]
url    = "roadmap"
name   = "Mapa vial"
weight = 7

[[languages.es.menu.main]]
url    = "downloads"
name   = "Descargas"
weight = 9


[[languages.es.menu.navmobile]]
url    = "https://forum.bitbay.market"
name   = "Comunidad"
weight = 1

[[languages.es.menu.navmobile]]
url    = "https://wallet.bitbay.market"
name   = "Web Wallet"
weight = 3

[[languages.en.menu.navmobile]]
url    = "https://wallet.bitbay.market/buy.php"
name   = "Buy $BAY"
weight = 5




[[languages.ar.menu.main]]
url    = "decentralized-marketplace"
name   = "اللامركزية"
weight = 1

[[languages.ar.menu.main]]
url    = "features"
name   = "المميزات"
weight = 3

[[languages.ar.menu.main]]
url    = "the-team"
name   = "الفريق"
weight = 5

[[languages.ar.menu.main]]
url    = "roadmap"
name   = "خارطة الطريق"
weight = 7

[[languages.ar.menu.main]]
url    = "downloads"
name   = "التحميلات"
weight = 9


[[languages.ar.menu.navmobile]]
url    = "https://forum.bitbay.market"
name   = "المجتمع"
weight = 1

[[languages.ar.menu.navmobile]]
url    = "https://wallet.bitbay.market"
name   = "محفظة الويب"
weight = 3

[[languages.ar.menu.navmobile]]
url    = "https://wallet.bitbay.market/buy.php"
name   = "شراء عملتنا"
weight = 5



[[languages.fr.menu.main]]
url    = "decentralized-marketplace"
name   = "Marché décentralisé"
weight = 1

[[languages.fr.menu.main]]
url    = "features"
name   = "Fonctionnalités"
weight = 3

[[languages.fr.menu.main]]
url    = "the-team"
name   = "L'équipe"
weight = 5

[[languages.fr.menu.main]]
url    = "roadmap"
name   = "Roadmap"
weight = 7

[[languages.fr.menu.main]]
url    = "downloads"
name   = "Téléchargements"
weight = 9


[[languages.fr.menu.navmobile]]
url    = "https://forum.bitbay.market"
name   = "Communauté"
weight = 1

[[languages.fr.menu.navmobile]]
url    = "https://wallet.bitbay.market"
name   = "Web Wallet"
weight = 3

[[languages.fr.menu.navmobile]]
url    = "https://wallet.bitbay.market/buy.php"
name   = "Acheter $BAY"
weight = 5



[[languages.ja.menu.main]]
url    = "fensanxingmaketsutofureisu"
name   = "分散型マーケットプレイス"
weight = 1

[[languages.ja.menu.main]]
url    = "features"
name   = "特徴・機能"
weight = 3

[[languages.ja.menu.main]]
url    = "the-team"
name   = "チーム"
weight = 5

[[languages.ja.menu.main]]
url    = "roadmap"
name   = "ロードマップ"
weight = 7

[[languages.ja.menu.main]]
url    = "downloads"
name   = "ダウンロード"
weight = 9


[[languages.ja.menu.navmobile]]
url    = "https://forum.bitbay.market"
name   = "コミュニティー"
weight = 1

[[languages.ja.menu.navmobile]]
url    = "https://wallet.bitbay.market"
name   = "ウェブウォレット"
weight = 3

[[languages.ja.menu.navmobile]]
url    = "https://wallet.bitbay.market/buy.php"
name   = "$BAY購入"
weight = 5



[[languages.ko.menu.main]]
url    = "bunsanhwadoen-makespeulleiseu"
name   = "분산화된 마켓플레이스"
weight = 1

[[languages.ko.menu.main]]
url    = "features"
name   = "기능들"
weight = 3

[[languages.ko.menu.main]]
url    = "the-team"
name   = "팀"
weight = 5

[[languages.ko.menu.main]]
url    = "roadmap"
name   = "로드맵"
weight = 7

[[languages.ko.menu.main]]
url    = "downloads"
name   = "다운로드"
weight = 9


[[languages.ko.menu.navmobile]]
url    = "https://forum.bitbay.market"
name   = "커뮤니티"
weight = 1

[[languages.ko.menu.navmobile]]
url    = "https://wallet.bitbay.market"
name   = "웹 지갑"
weight = 3

[[languages.ko.menu.navmobile]]
url    = "https://wallet.bitbay.market/buy.php"
name   = "$BAY 사기"
weight = 5




[[languages.pl.menu.main]]
url    = "zdecentralizowana-gielda"
name   = "Zdecentralizowana giełda"
weight = 1

[[languages.pl.menu.main]]
url    = "features"
name   = "Funkcje"
weight = 3

[[languages.pl.menu.main]]
url    = "the-team"
name   = "Zespół"
weight = 5

[[languages.pl.menu.main]]
url    = "roadmap"
name   = "Roadmap"
weight = 7

[[languages.pl.menu.main]]
url    = "downloads"
name   = "Pliki do pobrania"
weight = 9


[[languages.pl.menu.navmobile]]
url    = "https://forum.bitbay.market"
name   = "Społeczność"
weight = 1

[[languages.pl.menu.navmobile]]
url    = "https://wallet.bitbay.market"
name   = "Portfel na przeglądarkę"
weight = 3

[[languages.pl.menu.navmobile]]
url    = "https://wallet.bitbay.market/buy.php"
name   = "Kup $BAY"
weight = 5




[[languages.ru.menu.main]]
url    = "decentralizovannyy-rynok"
name   = "Децентрализованный Рынок"
weight = 1

[[languages.ru.menu.main]]
url    = "features"
name   = "Функции"
weight = 3

[[languages.ru.menu.main]]
url    = "the-team"
name   = "Команда"
weight = 5

[[languages.ru.menu.main]]
url    = "roadmap"
name   = "Дорожная карта"
weight = 7

[[languages.ru.menu.main]]
url    = "downloads"
name   = "Загрузки"
weight = 9


[[languages.ru.menu.navmobile]]
url    = "https://forum.bitbay.market"
name   = "Сообщество"
weight = 1

[[languages.ru.menu.navmobile]]
url    = "https://wallet.bitbay.market"
name   = "Веб-кошелек"
weight = 3

[[languages.ru.menu.navmobile]]
url    = "https://wallet.bitbay.market/buy.php"
name   = "купить $BAY"
weight = 5
